### ISSUE TITLE
HTML Course sections to be completed

### ISSUE THREAD

**Issue by MrOutWeb** [MrOutWeb/Learning_HTML#2]
## TODO

*Sections left to complete HTML Course*

* [ ] Structuring Your Content
* [ ] Images, Text and Links
* [ ] Going Further with HTML
